//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslatorApk.Resources.Files {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslatorApk.Resources.Files.FileResources", typeof(FileResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ab-&gt;ge
        ///aa-&gt;et
        ///af-&gt;za
        ///ak-&gt;gh
        ///sq-&gt;al
        ///am-&gt;et
        ///ar-&gt;ae
        ///an-&gt;es
        ///hy-&gt;am
        ///as-&gt;in
        ///av-&gt;az
        ///ay-&gt;bo
        ///az-&gt;az
        ///bm-&gt;ml
        ///ba-&gt;ru
        ///eu-&gt;es
        ///be-&gt;by
        ///bn-&gt;bd
        ///bh-&gt;in
        ///bi-&gt;vu
        ///bs-&gt;ba
        ///br-&gt;fr
        ///bg-&gt;bg
        ///my-&gt;mm
        ///ca-&gt;es
        ///ch-&gt;gu
        ///ce-&gt;ru
        ///ny-&gt;mw
        ///zh-&gt;cn
        ///cv-&gt;ru
        ///kw-&gt;gb
        ///co-&gt;fr
        ///cr-&gt;ca
        ///hr-&gt;hr
        ///cs-&gt;cz
        ///da-&gt;dk
        ///dv-&gt;mv
        ///nl-&gt;nl
        ///dz-&gt;bt
        ///en-&gt;gb
        ///et-&gt;ee
        ///ee-&gt;gh
        ///fo-&gt;fo
        ///fj-&gt;fj
        ///fi-&gt;fi
        ///fr-&gt;fr
        ///ff-&gt;sn
        ///gl-&gt;es
        ///gd-&gt;gb
        ///gv-&gt;im
        ///ka-&gt;ge
        ///de-&gt;de
        ///el-&gt;gr
        ///kl-&gt;dk
        ///gn-&gt;py
        ///gu-&gt;in
        ///ht-&gt;ht
        ///ha-&gt;ng
        ///he-&gt;il
        ///hz-&gt;na
        ///hi-&gt;in
        ///ho-&gt;pg
        ///hu-&gt;hu
        ///is-&gt;is
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string language_iso_to_country_iso {
            get {
                return ResourceManager.GetString("language_iso_to_country_iso", resourceCulture);
            }
        }
    }
}
