//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslatorApk.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslatorApk.Resources.Localizations.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        public static string AboutProgram {
            get {
                return ResourceManager.GetString("AboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер счёта скопирован в буфер обмена.
        /// </summary>
        public static string AccountNumberIsCopied {
            get {
                return ResourceManager.GetString("AccountNumberIsCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить язык.
        /// </summary>
        public static string AddLanguage {
            get {
                return ResourceManager.GetString("AddLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово!.
        /// </summary>
        public static string AllDone {
            get {
                return ResourceManager.GetString("AllDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все .smali.
        /// </summary>
        public static string AllSmali {
            get {
                return ResourceManager.GetString("AllSmali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все .xml.
        /// </summary>
        public static string AllXml {
            get {
                return ResourceManager.GetString("AllXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чередующиеся строки в редакторе.
        /// </summary>
        public static string AlternateRowsInEditor {
            get {
                return ResourceManager.GetString("AlternateRowsInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альтернативные клавиши редактирования:.
        /// </summary>
        public static string AlternativeEditingKeys {
            get {
                return ResourceManager.GetString("AlternativeEditingKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Андроид приложения.
        /// </summary>
        public static string AndroidApps {
            get {
                return ResourceManager.GetString("AndroidApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ api:.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ Api пуст.
        /// </summary>
        public static string ApiKeyIsEmpty {
            get {
                return ResourceManager.GetString("ApiKeyIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apktool не найден! Пожалуйста, загрузите apktool в &quot;Files\Resources\apktools&quot;.
        /// </summary>
        public static string ApktoolNotFound {
            get {
                return ResourceManager.GetString("ApktoolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия apktool:.
        /// </summary>
        public static string ApktoolVersion {
            get {
                return ResourceManager.GetString("ApktoolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить изменения?.
        /// </summary>
        public static string ApplyTheChanges {
            get {
                return ResourceManager.GetString("ApplyTheChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа.
        /// </summary>
        public static string AppSettings_Caption {
            get {
                return ResourceManager.GetString("AppSettings_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Собрать проект.
        /// </summary>
        public static string BuildProject {
            get {
                return ResourceManager.GetString("BuildProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается получить список версий apktools. Пожалуйста проверьте подключение к Интернету..
        /// </summary>
        public static string CanNotRecieveApktoolsList {
            get {
                return ResourceManager.GetString("CanNotRecieveApktoolsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается получить список плагинов. Пожалуйста, проверьте подключение к интернету..
        /// </summary>
        public static string CanNotRecievePluginsList {
            get {
                return ResourceManager.GetString("CanNotRecievePluginsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при переводе!.
        /// </summary>
        public static string CantTranslate {
            get {
                return ResourceManager.GetString("CantTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается обновить программу.
        /// </summary>
        public static string CantUpdateProgram {
            get {
                return ResourceManager.GetString("CantUpdateProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог.
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружение изменений.
        /// </summary>
        public static string ChangesDetector {
            get {
                return ResourceManager.GetString("ChangesDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание множества.
        /// </summary>
        public static string ChangesDetectorWindow_ManyFilesCreation {
            get {
                return ResourceManager.GetString("ChangesDetectorWindow_ManyFilesCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод множества.
        /// </summary>
        public static string ChangesDetectorWindow_ManyFilesTranslation {
            get {
                return ResourceManager.GetString("ChangesDetectorWindow_ManyFilesTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание одного.
        /// </summary>
        public static string ChangesDetectorWindow_OneFileCreation {
            get {
                return ResourceManager.GetString("ChangesDetectorWindow_OneFileCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод одного.
        /// </summary>
        public static string ChangesDetectorWindow_OneFileTranslation {
            get {
                return ResourceManager.GetString("ChangesDetectorWindow_OneFileTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод файла на основе словаря.
        /// </summary>
        public static string ChangesDetectorWindow_OneFileTranslation_ToolTip {
            get {
                return ResourceManager.GetString("ChangesDetectorWindow_OneFileTranslation_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите ячейку или строку!.
        /// </summary>
        public static string ChooseCellOrRow {
            get {
                return ResourceManager.GetString("ChooseCellOrRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать файл.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать папку.
        /// </summary>
        public static string ChooseFolder {
            get {
                return ResourceManager.GetString("ChooseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свернуть.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сборка завершена.
        /// </summary>
        public static string CompilationFinished {
            get {
                return ResourceManager.GetString("CompilationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий словарь.
        /// </summary>
        public static string CurrentDictionary {
            get {
                return ResourceManager.GetString("CurrentDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Декомпиляция завершена.
        /// </summary>
        public static string DecompilationFinished {
            get {
                return ResourceManager.GetString("DecompilationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Словари.
        /// </summary>
        public static string Dictionaries_Label {
            get {
                return ResourceManager.GetString("Dictionaries_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папки с словарями.
        /// </summary>
        public static string DictionariesFolder {
            get {
                return ResourceManager.GetString("DictionariesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Словарь.
        /// </summary>
        public static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы словарей.
        /// </summary>
        public static string DictionaryFiles {
            get {
                return ResourceManager.GetString("DictionaryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка словаря.
        /// </summary>
        public static string DictionaryFolder {
            get {
                return ResourceManager.GetString("DictionaryFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к директории файла (в буфер).
        /// </summary>
        public static string DirectoryPathToClipboard {
            get {
                return ResourceManager.GetString("DirectoryPathToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактор.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактор.
        /// </summary>
        public static string EditorSettings_Caption {
            get {
                return ResourceManager.GetString("EditorSettings_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустые папки.
        /// </summary>
        public static string EmptyFolders {
            get {
                return ResourceManager.GetString("EmptyFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустые smali.
        /// </summary>
        public static string EmptySmali {
            get {
                return ResourceManager.GetString("EmptySmali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустые xml.
        /// </summary>
        public static string EmptyXml {
            get {
                return ResourceManager.GetString("EmptyXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string ErrorLower {
            get {
                return ResourceManager.GetString("ErrorLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОШИБКА.
        /// </summary>
        public static string ErrorUpper {
            get {
                return ResourceManager.GetString("ErrorUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при компиляции!.
        /// </summary>
        public static string ErrorWhileCompiling {
            get {
                return ResourceManager.GetString("ErrorWhileCompiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при подписи!.
        /// </summary>
        public static string ErrorWhileSigning {
            get {
                return ResourceManager.GetString("ErrorWhileSigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружена ошибка (\&quot;{0}\&quot;), текст скопирован в буфер. Пожалуйста, отправьте её разработчику.
        /// </summary>
        public static string ExceptionOccured {
            get {
                return ResourceManager.GetString("ExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Развернуть.
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите удалить файл.
        /// </summary>
        public static string FileDeleteConfirmation {
            get {
                return ResourceManager.GetString("FileDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующий файл уже используется (и поэтому недоступен) другим пользователем или приложением: &quot;{0}&quot;.
        /// </summary>
        public static string FileIsInUse {
            get {
                return ResourceManager.GetString("FileIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл находится в.
        /// </summary>
        public static string FileIsSituatedIn {
            get {
                return ResourceManager.GetString("FileIsSituatedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название файла.
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя файла (в буфер).
        /// </summary>
        public static string FileNameToClipboard {
            get {
                return ResourceManager.GetString("FileNameToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы с ошибками.
        /// </summary>
        public static string FilesWithErrors {
            get {
                return ResourceManager.GetString("FilesWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти все.
        /// </summary>
        public static string FindAll {
            get {
                return ResourceManager.GetString("FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Искать далее.
        /// </summary>
        public static string FindNext {
            get {
                return ResourceManager.GetString("FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исправлять ошибки онлайн перевода:.
        /// </summary>
        public static string FixOnlineTranslationResults_Label {
            get {
                return ResourceManager.GetString("FixOnlineTranslationResults_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите удалить папку.
        /// </summary>
        public static string FolderDeleteConfirmation {
            get {
                return ResourceManager.GetString("FolderDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер шрифта:.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to из.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полный путь к файлу (в буфер).
        /// </summary>
        public static string FullFilePathToClipboard {
            get {
                return ResourceManager.GetString("FullFilePathToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер шрифта таблиц:.
        /// </summary>
        public static string GridFontSize {
            get {
                return ResourceManager.GetString("GridFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расширения изображений:.
        /// </summary>
        public static string ImageExtensions {
            get {
                return ResourceManager.GetString("ImageExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображения.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установлено.
        /// </summary>
        public static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abkhazian|Afar|Afrikaans|Akan|Albanian|Amharic|Arabic|Aragonese|Armenian|Assamese|Avaric|Avestan|Aymara|Azerbaijani|Bambara|Bashkir|Basque|Belarusian|Bengali (Bangla)|Bihari|Bislama|Bosnian|Breton|Bulgarian|Burmese|Catalan|Chamorro|Chechen|Chichewa, Chewa, Nyanja|Chinese|Chuvash|Cornish|Corsican|Cree|Croatian|Czech|Danish|Divehi, Dhivehi, Maldivian|Dutch|Dzongkha|English|Esperanto|Estonian|Ewe|Faroese|Fijian|Finnish|French|Fulah|Galician|Gaelic (Scottish)|Georgian|German|Greek|Greenlandic|Guarani|Gujarati|H [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ISOLongLanguages {
            get {
                return ResourceManager.GetString("ISOLongLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java не найдена! Пожалуйста, загрузите её с официального сайта или используйте портативную версию программы.
        /// </summary>
        public static string JavaNotFoundError {
            get {
                return ResourceManager.GetString("JavaNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык: .
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык не выбран!.
        /// </summary>
        public static string LanguageIsNotSelected {
            get {
                return ResourceManager.GetString("LanguageIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык приложения:.
        /// </summary>
        public static string LanguageOfApp {
            get {
                return ResourceManager.GetString("LanguageOfApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последняя версия.
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить с текстовыми строками.
        /// </summary>
        public static string LoadWithTextStrings {
            get {
                return ResourceManager.GetString("LoadWithTextStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учитывать регистр.
        /// </summary>
        public static string MatchCase {
            get {
                return ResourceManager.GetString("MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый язык:.
        /// </summary>
        public static string NewLanguage {
            get {
                return ResourceManager.GetString("NewLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый текст.
        /// </summary>
        public static string NewText {
            get {
                return ResourceManager.GetString("NewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует интернет соединение! Онлайн перевод недоступен.
        /// </summary>
        public static string NoInternetCantTranslate {
            get {
                return ResourceManager.GetString("NoInternetCantTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый текст.
        /// </summary>
        public static string OldText {
            get {
                return ResourceManager.GetString("OldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Албанский|Английский|Арабский|Армянский|Азербайджан|Африкаанс|Басков|Белорусский|Болгарский|Боснийский|Валлийский|Вьетнамский|Венгерский|Гаитянский (Креольский)|Галицкая|Голландский|Греческий|Грузинский|Датский|Идиш|Индонезийский|Ирландский|Итальянский|Исландский|Испанский|Казахский|Каталонский|Кыргызский|Китайский|Корейский|Латинский|Латвийский|Литовский|Малагасийский|Малайский|Мальтийский|Македонский|Монгольский|Немецкий|Норвежский|Персидский|Польский|Португальский|Румынский|Русский|Сербский|Словацкий|Сло [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OnlineTranslationsLongLanguages {
            get {
                return ResourceManager.GetString("OnlineTranslationsLongLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Онлайн переводчик:.
        /// </summary>
        public static string OnlineTranslator {
            get {
                return ResourceManager.GetString("OnlineTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только целые слова.
        /// </summary>
        public static string OnlyFullWords {
            get {
                return ResourceManager.GetString("OnlyFullWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только ресурсы.
        /// </summary>
        public static string OnlyResources {
            get {
                return ResourceManager.GetString("OnlyResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только xml.
        /// </summary>
        public static string OnlyXml {
            get {
                return ResourceManager.GetString("OnlyXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть в проводнике.
        /// </summary>
        public static string OpenInExplorer {
            get {
                return ResourceManager.GetString("OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть с помощью.
        /// </summary>
        public static string OpenWith {
            get {
                return ResourceManager.GetString("OpenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опции.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расширения других файлов:.
        /// </summary>
        public static string OtherExtensions {
            get {
                return ResourceManager.GetString("OtherExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другие файлы.
        /// </summary>
        public static string OtherFiles {
            get {
                return ResourceManager.GetString("OtherFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плагины.
        /// </summary>
        public static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить языки.
        /// </summary>
        public static string RemoveLanguages {
            get {
                return ResourceManager.GetString("RemoveLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заменить.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заменять последовательности Юникода.
        /// </summary>
        public static string ReplaceUnicodeSequences {
            get {
                return ResourceManager.GetString("ReplaceUnicodeSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перезапустить программу для смены языка?.
        /// </summary>
        public static string RestartProgramToApplyLanguage {
            get {
                return ResourceManager.GetString("RestartProgramToApplyLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка с результатом.
        /// </summary>
        public static string ResultFolder {
            get {
                return ResourceManager.GetString("ResultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить и выйти.
        /// </summary>
        public static string SaveAndExit {
            get {
                return ResourceManager.GetString("SaveAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окно редактора было закрыто. Поиск работать не будет.
        /// </summary>
        public static string SearchEditorClosed {
            get {
                return ResourceManager.GetString("SearchEditorClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опции поиска.
        /// </summary>
        public static string SearchOptions {
            get {
                return ResourceManager.GetString("SearchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать папку перед поиском!.
        /// </summary>
        public static string SearchWindow_FolderIsNotSelected {
            get {
                return ResourceManager.GetString("SearchWindow_FolderIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите папку:.
        /// </summary>
        public static string SelectAFolder {
            get {
                return ResourceManager.GetString("SelectAFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоперевод по словарю сессии:.
        /// </summary>
        public static string SessionAutoTranslation {
            get {
                return ResourceManager.GetString("SessionAutoTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать в проводнике.
        /// </summary>
        public static string ShowInExplorer {
            get {
                return ResourceManager.GetString("ShowInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать уведомления:.
        /// </summary>
        public static string ShowNotifications {
            get {
                return ResourceManager.GetString("ShowNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать превью изображений:.
        /// </summary>
        public static string ShowPreview {
            get {
                return ResourceManager.GetString("ShowPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подписать.
        /// </summary>
        public static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исходная папка.
        /// </summary>
        public static string SourceFolder {
            get {
                return ResourceManager.GetString("SourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующая.
        /// </summary>
        public static string StringEditorWindow_NextStringLabel {
            get {
                return ResourceManager.GetString("StringEditorWindow_NextStringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущая.
        /// </summary>
        public static string StringEditorWindow_PreviousStringLabel {
            get {
                return ResourceManager.GetString("StringEditorWindow_PreviousStringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переведено строк:.
        /// </summary>
        public static string StringsTranslated {
            get {
                return ResourceManager.GetString("StringsTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целевой язык.
        /// </summary>
        public static string TargetLanguage {
            get {
                return ResourceManager.GetString("TargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заданный текст не найден.
        /// </summary>
        public static string TextNotFound {
            get {
                return ResourceManager.GetString("TextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл повреждён!.
        /// </summary>
        public static string TheFileIsCorrupted {
            get {
                return ResourceManager.GetString("TheFileIsCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующие файлы уже добавлены.
        /// </summary>
        public static string TheFollowingFilesHaveBeenAlreadyAdded {
            get {
                return ResourceManager.GetString("TheFollowingFilesHaveBeenAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема:.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темная.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Светлая.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поверх всех окон:.
        /// </summary>
        public static string TopMost {
            get {
                return ResourceManager.GetString("TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевести всё.
        /// </summary>
        public static string TranslateAll {
            get {
                return ResourceManager.GetString("TranslateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка с переводами.
        /// </summary>
        public static string TranslatedFolder {
            get {
                return ResourceManager.GetString("TranslatedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод.
        /// </summary>
        public static string TranslationSettings_Caption {
            get {
                return ResourceManager.GetString("TranslationSettings_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тайм-аут перевода:.
        /// </summary>
        public static string TranslationTimeout_Label {
            get {
                return ResourceManager.GetString("TranslationTimeout_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружена непредвиденная ошибка, текст ошибки в буфере обмена.
        /// </summary>
        public static string UnhandledExceptionOccured {
            get {
                return ResourceManager.GetString("UnhandledExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступна новая версия. Обновить?.
        /// </summary>
        public static string UpdateNewVersion {
            get {
                return ResourceManager.GetString("UpdateNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание завершения операции....
        /// </summary>
        public static string WaitingOperation {
            get {
                return ResourceManager.GetString("WaitingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы xml.
        /// </summary>
        public static string XmlFiles {
            get {
                return ResourceManager.GetString("XmlFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактор правил xml.
        /// </summary>
        public static string XmlRulesEditor {
            get {
                return ResourceManager.GetString("XmlRulesEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать словарь!.
        /// </summary>
        public static string YouNeedToChooseDictionary {
            get {
                return ResourceManager.GetString("YouNeedToChooseDictionary", resourceCulture);
            }
        }
    }
}
