//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslatorApk.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslatorApk.Resources.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string AboutProgram {
            get {
                return ResourceManager.GetString("AboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account number is copied to the clipboard.
        /// </summary>
        public static string AccountNumberIsCopied {
            get {
                return ResourceManager.GetString("AccountNumberIsCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add language.
        /// </summary>
        public static string AddLanguage {
            get {
                return ResourceManager.GetString("AddLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All done!.
        /// </summary>
        public static string AllDone {
            get {
                return ResourceManager.GetString("AllDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All .smali.
        /// </summary>
        public static string AllSmali {
            get {
                return ResourceManager.GetString("AllSmali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All .xml.
        /// </summary>
        public static string AllXml {
            get {
                return ResourceManager.GetString("AllXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alternate rows in editor.
        /// </summary>
        public static string AlternateRowsInEditor {
            get {
                return ResourceManager.GetString("AlternateRowsInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alternative editing keys:.
        /// </summary>
        public static string AlternativeEditingKeys {
            get {
                return ResourceManager.GetString("AlternativeEditingKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Android apps.
        /// </summary>
        public static string AndroidApps {
            get {
                return ResourceManager.GetString("AndroidApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Api key:.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Api key is empty.
        /// </summary>
        public static string ApiKeyIsEmpty {
            get {
                return ResourceManager.GetString("ApiKeyIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apktool is not found! Please, download apktool to &quot;Files\Resources\apktools&quot;.
        /// </summary>
        public static string ApktoolNotFound {
            get {
                return ResourceManager.GetString("ApktoolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apktool version:.
        /// </summary>
        public static string ApktoolVersion {
            get {
                return ResourceManager.GetString("ApktoolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply the changes?.
        /// </summary>
        public static string ApplyTheChanges {
            get {
                return ResourceManager.GetString("ApplyTheChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Build project.
        /// </summary>
        public static string BuildProject {
            get {
                return ResourceManager.GetString("BuildProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can not recieve apktools list. Please, check your internet connection..
        /// </summary>
        public static string CanNotRecieveApktoolsList {
            get {
                return ResourceManager.GetString("CanNotRecieveApktoolsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can not recieve plugins list. Please, check your internet connection..
        /// </summary>
        public static string CanNotRecievePluginsList {
            get {
                return ResourceManager.GetString("CanNotRecievePluginsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error was occurred while translating!.
        /// </summary>
        public static string CantTranslate {
            get {
                return ResourceManager.GetString("CantTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t update program.
        /// </summary>
        public static string CantUpdateProgram {
            get {
                return ResourceManager.GetString("CantUpdateProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Catalog.
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changes detector.
        /// </summary>
        public static string ChangesDetector {
            get {
                return ResourceManager.GetString("ChangesDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Many files creation.
        /// </summary>
        public static string ChangesDetectorWindow_ManyFilesCreation {
            get {
                return ResourceManager.GetString("ChangesDetectorWindow_ManyFilesCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Many files translation.
        /// </summary>
        public static string ChangesDetectorWindow_ManyFilesTranslation {
            get {
                return ResourceManager.GetString("ChangesDetectorWindow_ManyFilesTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One file creation.
        /// </summary>
        public static string ChangesDetectorWindow_OneFileCreation {
            get {
                return ResourceManager.GetString("ChangesDetectorWindow_OneFileCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One file translation.
        /// </summary>
        public static string ChangesDetectorWindow_OneFileTranslation {
            get {
                return ResourceManager.GetString("ChangesDetectorWindow_OneFileTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One file translation with dictionary.
        /// </summary>
        public static string ChangesDetectorWindow_OneFileTranslation_ToolTip {
            get {
                return ResourceManager.GetString("ChangesDetectorWindow_OneFileTranslation_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose cell or row!.
        /// </summary>
        public static string ChooseCellOrRow {
            get {
                return ResourceManager.GetString("ChooseCellOrRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose file.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose folder.
        /// </summary>
        public static string ChooseFolder {
            get {
                return ResourceManager.GetString("ChooseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collapse.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compilation finished.
        /// </summary>
        public static string CompilationFinished {
            get {
                return ResourceManager.GetString("CompilationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current dictionary.
        /// </summary>
        public static string CurrentDictionary {
            get {
                return ResourceManager.GetString("CurrentDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decompilation finished.
        /// </summary>
        public static string DecompilationFinished {
            get {
                return ResourceManager.GetString("DecompilationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder with dictionaries.
        /// </summary>
        public static string DictionariesFolder {
            get {
                return ResourceManager.GetString("DictionariesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dictionary.
        /// </summary>
        public static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dictionary files.
        /// </summary>
        public static string DictionaryFiles {
            get {
                return ResourceManager.GetString("DictionaryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dictionary&apos;s folder.
        /// </summary>
        public static string DictionaryFolder {
            get {
                return ResourceManager.GetString("DictionaryFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Directory path (to clipboard).
        /// </summary>
        public static string DirectoryPathToClipboard {
            get {
                return ResourceManager.GetString("DirectoryPathToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Editor.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty folders.
        /// </summary>
        public static string EmptyFolders {
            get {
                return ResourceManager.GetString("EmptyFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty smali.
        /// </summary>
        public static string EmptySmali {
            get {
                return ResourceManager.GetString("EmptySmali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty xml.
        /// </summary>
        public static string EmptyXml {
            get {
                return ResourceManager.GetString("EmptyXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string ErrorLower {
            get {
                return ResourceManager.GetString("ErrorLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ERROR.
        /// </summary>
        public static string ErrorUpper {
            get {
                return ResourceManager.GetString("ErrorUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while compiling!.
        /// </summary>
        public static string ErrorWhileCompiling {
            get {
                return ResourceManager.GetString("ErrorWhileCompiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while signing!.
        /// </summary>
        public static string ErrorWhileSigning {
            get {
                return ResourceManager.GetString("ErrorWhileSigning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expand.
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you really want to delete the file.
        /// </summary>
        public static string FileDeleteConfirmation {
            get {
                return ResourceManager.GetString("FileDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file may be in use (and thus locked) by another user or application: &quot;{0}&quot;.
        /// </summary>
        public static string FileIsInUse {
            get {
                return ResourceManager.GetString("FileIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File is situated in.
        /// </summary>
        public static string FileIsSituatedIn {
            get {
                return ResourceManager.GetString("FileIsSituatedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filename.
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File name (to clipboard).
        /// </summary>
        public static string FileNameToClipboard {
            get {
                return ResourceManager.GetString("FileNameToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Files with errors.
        /// </summary>
        public static string FilesWithErrors {
            get {
                return ResourceManager.GetString("FilesWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find all.
        /// </summary>
        public static string FindAll {
            get {
                return ResourceManager.GetString("FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find next.
        /// </summary>
        public static string FindNext {
            get {
                return ResourceManager.GetString("FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you really want to delete the folder.
        /// </summary>
        public static string FolderDeleteConfirmation {
            get {
                return ResourceManager.GetString("FolderDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на from.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full file path (to clipboard).
        /// </summary>
        public static string FullFilePathToClipboard {
            get {
                return ResourceManager.GetString("FullFilePathToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Visible file extensions:.
        /// </summary>
        public static string ImageExtensions {
            get {
                return ResourceManager.GetString("ImageExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installed.
        /// </summary>
        public static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Java wasn&apos;t found! Please, download it from official site or use portable version of program.
        /// </summary>
        public static string JavaNotFoundError {
            get {
                return ResourceManager.GetString("JavaNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language: .
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language is not selected!.
        /// </summary>
        public static string LanguageIsNotSelected {
            get {
                return ResourceManager.GetString("LanguageIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language of app:.
        /// </summary>
        public static string LanguageOfApp {
            get {
                return ResourceManager.GetString("LanguageOfApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Latest version.
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load with text strings.
        /// </summary>
        public static string LoadWithTextStrings {
            get {
                return ResourceManager.GetString("LoadWithTextStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Match case.
        /// </summary>
        public static string MatchCase {
            get {
                return ResourceManager.GetString("MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English (UK)|Arabic|Afrikaans|Belarusian|Bulgarian|Bosnian|Hungarian|Vietnamese|Dutch|Greek|Danish|Zulu|Hebrew|Indonesian|Spanish|Italian|Catalan|Chinese|Chinese (Simplified)|Chinese (Traditional)|Latvian|Lithuanian|Malay|German|Norwegian|Persian|Polish|Portuguese|Romanian|Russian|Serbian|Slovak|Slovenian|Swahili|Tagalog|Thai|Turkish|Ukrainian|Finnish|French|Hindi|Czech|Swedish|Estonian|Japanese.
        /// </summary>
        public static string NamesOfFolderLanguages {
            get {
                return ResourceManager.GetString("NamesOfFolderLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New language:.
        /// </summary>
        public static string NewLanguage {
            get {
                return ResourceManager.GetString("NewLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New text.
        /// </summary>
        public static string NewText {
            get {
                return ResourceManager.GetString("NewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error while connecting to the internet! Online translation is disabled.
        /// </summary>
        public static string NoInternetCantTranslate {
            get {
                return ResourceManager.GetString("NoInternetCantTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old text.
        /// </summary>
        public static string OldText {
            get {
                return ResourceManager.GetString("OldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Albanian|English|Arabic|Armenian|Azerbaijan|Afrikaans|Basque|Belarusian|Bulgarian|Bosnian|Welsh|Vietnamese|Hungarian|Haitian(Creole)|Galician|Dutch|Greek|Georgian|Danish|Yiddish|Indonesian|Irish|Italian|Icelandic|Spanish|Kazakh|Catalan|Kyrgyz|Chinese|Korean|Latin|Latvian|Lithuanian|Malagasy|Malay|Maltese|Macedonian|Mongolian|German|Norwegian|Persian|Polish|Portuguese|Romanian|Russian|Serbian|Slovakian|Slovenian|Swahili|Tajik|Thai|Tagalog|Tatar|Turkish|Uzbek|Ukrainian|Finish|French|Croatian|Czech|Swedish|Est [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string OnlineTranslationsLongLanguages {
            get {
                return ResourceManager.GetString("OnlineTranslationsLongLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Online translator:.
        /// </summary>
        public static string OnlineTranslator {
            get {
                return ResourceManager.GetString("OnlineTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Match whole word only.
        /// </summary>
        public static string OnlyFullWords {
            get {
                return ResourceManager.GetString("OnlyFullWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only resources.
        /// </summary>
        public static string OnlyResources {
            get {
                return ResourceManager.GetString("OnlyResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only xml.
        /// </summary>
        public static string OnlyXml {
            get {
                return ResourceManager.GetString("OnlyXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open in explorer.
        /// </summary>
        public static string OpenInExplorer {
            get {
                return ResourceManager.GetString("OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open with.
        /// </summary>
        public static string OpenWith {
            get {
                return ResourceManager.GetString("OpenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other extensions:.
        /// </summary>
        public static string OtherExtensions {
            get {
                return ResourceManager.GetString("OtherExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other files.
        /// </summary>
        public static string OtherFiles {
            get {
                return ResourceManager.GetString("OtherFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Plugins.
        /// </summary>
        public static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace Unicode sequences.
        /// </summary>
        public static string ReplaceUnicodeSequences {
            get {
                return ResourceManager.GetString("ReplaceUnicodeSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart program to apply language setting?.
        /// </summary>
        public static string RestartProgramToApplyLanguage {
            get {
                return ResourceManager.GetString("RestartProgramToApplyLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Result folder.
        /// </summary>
        public static string ResultFolder {
            get {
                return ResourceManager.GetString("ResultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save and exit.
        /// </summary>
        public static string SaveAndExit {
            get {
                return ResourceManager.GetString("SaveAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Editor window was closed. Search will not work.
        /// </summary>
        public static string SearchEditorClosed {
            get {
                return ResourceManager.GetString("SearchEditorClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search options.
        /// </summary>
        public static string SearchOptions {
            get {
                return ResourceManager.GetString("SearchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must select a folder to search!.
        /// </summary>
        public static string SearchWindow_FolderIsNotSelected {
            get {
                return ResourceManager.GetString("SearchWindow_FolderIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a folder:.
        /// </summary>
        public static string SelectAFolder {
            get {
                return ResourceManager.GetString("SelectAFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto translation with session dictionary:.
        /// </summary>
        public static string SessionAutoTranslation {
            get {
                return ResourceManager.GetString("SessionAutoTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show in explorer.
        /// </summary>
        public static string ShowInExplorer {
            get {
                return ResourceManager.GetString("ShowInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show notifications:.
        /// </summary>
        public static string ShowNotifications {
            get {
                return ResourceManager.GetString("ShowNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show preview:.
        /// </summary>
        public static string ShowPreview {
            get {
                return ResourceManager.GetString("ShowPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign.
        /// </summary>
        public static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Source folder.
        /// </summary>
        public static string SourceFolder {
            get {
                return ResourceManager.GetString("SourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        public static string StringEditorWindow_NextStringLabel {
            get {
                return ResourceManager.GetString("StringEditorWindow_NextStringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous.
        /// </summary>
        public static string StringEditorWindow_PreviousStringLabel {
            get {
                return ResourceManager.GetString("StringEditorWindow_PreviousStringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Strings translated:.
        /// </summary>
        public static string StringsTranslated {
            get {
                return ResourceManager.GetString("StringsTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Target language.
        /// </summary>
        public static string TargetLanguage {
            get {
                return ResourceManager.GetString("TargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text is not found.
        /// </summary>
        public static string TextNotFound {
            get {
                return ResourceManager.GetString("TextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file is corrupted!.
        /// </summary>
        public static string TheFileIsCorrupted {
            get {
                return ResourceManager.GetString("TheFileIsCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The following files have been already added.
        /// </summary>
        public static string TheFollowingFilesHaveBeenAlreadyAdded {
            get {
                return ResourceManager.GetString("TheFollowingFilesHaveBeenAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme:.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On top of all windows:.
        /// </summary>
        public static string TopMost {
            get {
                return ResourceManager.GetString("TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translate all.
        /// </summary>
        public static string TranslateAll {
            get {
                return ResourceManager.GetString("TranslateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder with translations.
        /// </summary>
        public static string TranslatedFolder {
            get {
                return ResourceManager.GetString("TranslatedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uninstall.
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New version is available. Update?.
        /// </summary>
        public static string UpdateNewVersion {
            get {
                return ResourceManager.GetString("UpdateNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waiting for completion of the operation....
        /// </summary>
        public static string WaitingOperation {
            get {
                return ResourceManager.GetString("WaitingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Xml files.
        /// </summary>
        public static string XmlFiles {
            get {
                return ResourceManager.GetString("XmlFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на XmlRulesEditor.
        /// </summary>
        public static string XmlRulesEditor {
            get {
                return ResourceManager.GetString("XmlRulesEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You need to choose dictionary!.
        /// </summary>
        public static string YouNeedToChooseDictionary {
            get {
                return ResourceManager.GetString("YouNeedToChooseDictionary", resourceCulture);
            }
        }
    }
}
